/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpFullscreen: typeof import('~icons/ep/fullscreen')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpFullSreen: typeof import('~icons/ep/full-sreen')['default']
    IEpMicrophone: typeof import('~icons/ep/microphone')['default']
    IEpMonitor: typeof import('~icons/ep/monitor')['default']
    IEpMoreFilled: typeof import('~icons/ep/more-filled')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpVideoCamera: typeof import('~icons/ep/video-camera')['default']
    IEpVideopause: typeof import('~icons/ep/videopause')['default']
    IEpVideoPause: typeof import('~icons/ep/video-pause')['default']
    IEpVideoplay: typeof import('~icons/ep/videoplay')['default']
    IEpVideoPlay: typeof import('~icons/ep/video-play')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
